### ISSUE TITLE
Remove friction from PAID user experience

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/ideas#198]
## TODOs

**CRUD Dashboard > Getting Started**
- [ ] SHOULD - generate CrudController without Request, to eliminate a step - fixed by `php artisan backpack:crud --no-request` in https://github.com/Laravel-Backpack/Generators/issues/137
- [ ] SHOULD - show all videos in a course format, highlight that you've already done one video of seven, only six more to go; 
- [ ] MUST - on last step, before hiding the notice, tell people to buy DevTools, PRO or EditableColumns, each with their benefits; and link to the FREE vs PRO table; or maybe that should be step 3 (optional) and move "_hide this notice_" to step 4?
- [ ] 

**Docs > Video Course**
- [ ] SHOULD - split longer video into shorter one - 2-3-4 minutes max;
- [ ] SHOULD - keep info about what I've already watched in LocalStorage and DB if logged in; tell visitor to create an account or log in, in order to permanently store their video progress;
- [ ] SHOULD - tell the visitor to create an account at the end of each video?
- [ ] MUST - videos don't make it clear what's FREE and what's PAID; videos don't do a good job at convincing people to buy PRO or DevTools; make it clear in the videos when you're using FREE features and PAID features; show how much faster things are done if using DevTools; maybe we make separate videos about generating CRUDs, one FREE and one PAID?

**Website > Cart**
- [ ] MUST - upsell bubble (buy our addons) is unconvincing; why not list a few benefits here? I'd be more likely to be interested; maybe make this prettier too;
- [ ] MUST - DevTools page needs a video; fast! I can't be bothered with reading all of these things; if you don't make it dead-simple to me to understand why I should buy this, I won't; GIF is ok... video would do a lot more;
- [ ] COULD - pre-select country based on IP, or the last invoice (if available);
- [ ] SHOULD - add an Edit button to the proforma invoice, allowing me to re-start the cart submission process with different company info, or add something else to the cart;
- [ ] MUST - after I paid, you show me the step 3/3 (final invoice); that's ok, but at that point that's not the main thing I'm interested in; the main thing right now is "_how do I use what I bought_"; perhaps:
    - [ ] MUST - send an email confirming the purchase
    - [ ] MUST - polish the instructions page, so it also includes instructions on how to install backpack/pro, backpack/devtools and all; we can even output the token and instructions here, why take me to the product page, which takes me to the tokens page? maaan; just tell me to do `php artisan backpack:require-pro` and to use this token and password, that’s it; 
    - [ ] MUST - also, I just gave you money; make me feel good about my purchase; tell me about all the things I get to do now, thanks to my purchase; 
    - [ ] SHOULD - make it even easier to install what I bought, by adding some optional parameters to the `php artisan backpack:require:pro --token=8a0sas0 --password=8a9huahda` - that way when we give the instructions they'll just need to copy-paste this one line and they're done, no prompts;
    - [ ] COULD - in the command line, after I've installed a paid addon, why not make me feel good about my purchase? why not tell me that "_You now have access to 50+ more fields, 10+ more column types, filters, charts an much more. See a list of PRO features and how to use them here: link_"; different copy for each paid addon, of course;

**Website > Register**
- [ ] MUST - because I went to "sign up", then "register", after I've created my account I was not redirected back to the cart; that's a bug, right there; remember where I started, then take me back there, so I can finish giving you money;
- [ ] SHOULD - you didn't ask me to confirm my email, bad;
- [ ] MUST - you subscribed me to the security newsletter, automatically, and shown me a bubble to opt out; that's sneaky and non-GDPR; please create an interstitial page or a modal, after I've verified my account, to ask me about my email preferences: both the security newsletter (where you can make it clear how important it is) and the blog article digest; if I quit, you can bug me about me not "finishing my account setup"; first, online; afterwards (maybe) send me an email;

**Website > My Account**
- [ ] SHOULD - It’s confusing that in my sidebar menu, I’m seeing a “Tokens v5” where I have something and “Licenses v4” where I have nothing… just saying… Let's hide v4 if no licenses are there, v5 has been launched for 6 months already;
- [ ] MUST - replace installation docs in PRO, DevTools and Editable-Column; instead of doing the process manually, recommend running `php artisan backpack:require:pro` - that's much easier; keep manual process just in case, but as a secondary option;

**Website > Emails**
- [ ] MUST - 7/14 days have passed after my purchase, I have a good idea of Backpack now, and it's helped me create a big chunk of the admin panel; this is a PERFECT time for you to ask for feedback - how it's going, how I like it, what I had problems with; but you haven't; DO IT; send a text email 7 days after purchase, asking how they like it so far, if they hit any major problems building their admin panels;
- [ ] MUST - 3 weeks have passed since my purchase; this is a great time for you to give me a discount; maybe a 25% discount to upgrade to UNLIMITED (299 EUR) or EVERYTHING (449 EUR)?
- [ ] MUST - 1 month after purchase, ask for a testimonial;
- [ ] MUST - 1 day after putting a new project online, ask for a testimonial;
- [ ] SHOULD - 3-4 days after sign-up, if the visitor hasn't watched all videos (or finished the entire course), send them an email with links, and a reminder all of them are important to watch, to make it easy to work with Backpack;
- [ ] MUST - 11.5 months have passed since my purchase; you want me to buy again, right? why not remind me, and give me an incentive to buy right away, before my access expires? give me 10-15-20% discount to purchase again in the next 2 weeks, and I'll probably do it;
- [ ] MUST - 1 week till my access expires; last chance to buy at a discount, right? email me _again_ to purchase at a discount - last chance;
- [ ] MUST - my access to a paid package has expired; email me to let me know I should start using a fixed version from now on; or alternatively... buy more access at full price;

**Comment by tabacitu** [comment]
Note to self: I love how simple and effective this landing page is - https://slite.com/?redirect=no
